### ISSUE TITLE
Angular 6.0.0-beta7 can't be installed

### ISSUE THREAD

**Issue by mashbrno** [tomastrajan/angular-ngrx-material-starter#125]
During `npm install` I have problem with angular 6.0.0-beta7 because it references `github:webpack-contrib/html-webpack-plugin` which doesn't exist anymore. I tried to update to 6.0.0-rc.2, but got another issue with `Local workspace file ('angular.json') could not be found.`

Can you please help me?

**Comment by bretonio** [comment]
I have the same difficulty since yesterday. I am prompted for my `.ssh` key and then,

```

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/webpack-contrib/html-webpack-plugin.git
npm ERR! 
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

```
I checked for my existing SSH and studied the [tutorial on generating and adding these](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/).

Thanks for your kind attention.

**Comment by JanOschii** [comment]
Seems to be a bug with angular/core. I have had the same problem and the easy way I found was downgrading all angular dependencies to "Latest" (5.2.9 mostly). Now everything is fine again. 
If you use Visual Code, then you should take a look to the "Version Lens" extension for VS. 
Its a live saver for jobs like this.

**Comment by aetherity** [comment]
Same issue.

**Comment by GuateDevIO** [comment]
Had the same issue and after an hour of investigation, it seems that the issue is found here:
See text below headline: "If you use HtmlWebpackPlugin“ on https://medium.com/webpack/webpack-4-released-today-6cdb994702d4

To fix this I replace the blow:

https://github.com/tomastrajan/angular-ngrx-material-starter/blob/3e7a6217c83943310b260607be27183f837d14fc/package-lock.json#L106

Replace it with this:
`"html-webpack-plugin": "3.2.0",`

https://github.com/tomastrajan/angular-ngrx-material-starter/blob/3e7a6217c83943310b260607be27183f837d14fc/package-lock.json#L5967

Replace it with this:
`"version": "3.2.0",`

Hope it helps.

**Comment by tomastrajan** [comment]
Hey! Thank you very much for debugging this issue! I hope that this will all go away soon with releases of stable 6.0.0 of Angular, Material, RxJS and CLI. Until than the workaround with the html-webpack-plugin version seem to be the way to go!

**Comment by aetherity** [comment]
This resolved the install issue.  Thanks!

**Comment by tomastrajan** [comment]
Started working on migration to 6.0.0-rc versions of Angular, CLI, Material, NgRx and RxJS. It seems to mostly work in dev mode but I still have issues with running tests and lazy loaded ngrx modules so it might take a while or even until real 6.0.0 until all things play nicely together.

**Comment by tomastrajan** [comment]
Feel free to check [this huge commit](https://github.com/tomastrajan/angular-ngrx-material-starter/commit/9a41534bc6c6d8cf1e39bdf303e9bfe4e2ffa3a5) which contains migration to the new Angular CLI project configuration and layout.

Also version of starter project was aligned with Angular and others so starter is currently having `6.0.0-rc.1`.

Hope that helps!
