### ISSUE TITLE
FontAwesome usage seems to break mat-*-stepper

### ISSUE THREAD

**Issue by ianfdk** [tomastrajan/angular-ngrx-material-starter#288]
The steppers from MaterialStepperModule are adding a pencil icon to the completed steps. See https://material.angular.io/components/stepper/overview and fill out the first step to see the "1" change into a pencil icon.

The markup added by the component is `<mat-icon class="mat-icon material-icons ng-star-inserted" role="img" aria-hidden="true" style="">create</mat-icon>`. 

The `material-icons` class does not exist, therefore what should be an icon displays as "create" string.

This commit https://github.com/tomastrajan/angular-ngrx-material-starter/commit/26b0cf2 seems to be the culprit, since it removed `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">` from index.html.

It is a bit off-putting to have to add the following markup any time you want to create a stepper
```
<ng-template matStepperIcon="edit">
  <mat-icon fontSet="fas" fontIcon="fa-pencil-alt"></mat-icon>
</ng-template>
```

Was this overlooked in the decision to use FontAwesome? Is there some sort of global config that I'm missing? Was this intended and I should just live with it?

Thank you

**Comment by tomastrajan** [comment]
Hi @ianfdk !

Thank you very much for a very detailed report of the issue! 

The idea behind removing of the Material Icons dependency was to reduce page size and resulting page load time. The choice to go with Font Awesome was influenced by the starter project specific need for brand (social) icons that are used in title page, top toolbar and footer.

Also, I had repeated subjective experience of having much easier time finding relevant icon in the Font Awesome library for the envisioned use case.

These reasons resulted in a refactor which migrated all used icons to Font Awesome while leveraging configuration capabilities of Angular Material `<mat-icon>` component.

I understand and can appreciate overhead that this solution introduces for the other Angular Material use cases like using provided `MatSteperModule`. It is great that you also described how this can be worked around! I do agree that the overhead can be considered too much in case stepper is used multiple times through the application.

Please feel free to switch back to Material Icons in your application if it provides you with better developer experience.

I will definitely add this in the "Troubleshooting" section in README.md for users that are interested in using MatSteperModule.

Also, it would be probably worth implementing an example page (next to todos, stock market, ...) that shows how to implement stepper because there were already multiple requests and questions about this component.

Anyway, thank you again and wish you a great day!
