### ISSUE TITLE
Architecture Specification

### ISSUE THREAD

**Issue by ewertonews** [tomastrajan/angular-ngrx-material-starter#468]
## Describe the feature you'd like:
It would nice to have a picture/diagram representing the architecture of the template. What are the modules, components and how they interact with each other and so on.  It would help people to better understand the template code.
## Other information:
N/A
## I would be willing to submit a PR to fix this issue:

[ ] Yes (Assistance is provided if you need help submitting a pull request)  
[x] No

**Comment by jcox86** [comment]
@ewertonews Have you tried running and exploring though [Compodoc](https://compodoc.app/) against this project?  This project has a dev dependency on it.  Compodoc works on many Angular projects for what you are describing.

**Comment by tomastrajan** [comment]
@ewertonews @jcox86 the compodoc was removed as I think it is best to keep starter as lean as possible, besides that it's a great advice and feel free to add it when you use it on your own, maybe we can add note in readme.

I just wanted to reduce complexity of the starter because it became very bloated over the years!
