### ISSUE TITLE
Do not import Shared Module in AppModule

### ISSUE THREAD

**Issue by cynx** [tomastrajan/angular-ngrx-material-starter#47]
as per style guide, shared module is intended to be imported only in feature modules and not in app or core.

**Comment by tomastrajan** [comment]
I was reading the style guide right now but I can't find the place where the import of shared module in app module is discouraged? I only found 

> Do declare components, directives, and pipes in a shared module when those items will be re-used and referenced by the components declared in other feature modules.
> 
> Consider using the name SharedModule when the contents of a shared module are referenced across the entire application.
> 
> Avoid providing services in shared modules. Services are usually singletons that are provided once for the entire application or in a particular feature module.

From this I understand that it's about components (pipes, directives, ...) which are used `across the entire` application. Which includes also app component which implements the main layout like toolbar, sidenav and footer so it needs access to these material components.

I fully agree with not including any services (providers) in shared module because they would end up with multiple instances instead of singleton.

So please, can you elaborate bit more on why not to include shared module in app module?

**Comment by Fiontan** [comment]
@cynx  In my opinion, this is an incorrect interpretation and I have imported SharedModule into whatever module needs its functionality, including the AppModule, which conforms to @tomastrajan 's approach. For example, FeatureModuleX contains some Material components, the Modules of which are imported in a MaterialComponentsModule (and exported) into SharedModule. SharedModule is imported into AppModule, because AppModule has components that need Material functionality. FeatureModuleX is lazy loaded and so must also import SharedModule.

**Comment by tomastrajan** [comment]
I consider this question answered and closing the issue, in case you have more arguments please open a new issue, thank you for your contribution!
