### ISSUE TITLE
A router path with full screen?

### ISSUE THREAD

**Issue by goforu** [tomastrajan/angular-ngrx-material-starter#515]
Hi, I want to have a full screen page with no sidebar toolbar etc.
How can I achieve that?

**Comment by tomastrajan** [comment]
@goforu I am not sure if I understand ? Can you please provide screenshot?

**Comment by goforu** [comment]
for say.. like I want to create an isolated login page, I add my path to the router as below.
![image](https://user-images.githubusercontent.com/5236864/75032268-226b7b00-54e3-11ea-94c2-7b4fd3079a2d.png)
It shows in the middle of the page with toolbar, footer and so on because the outlet tag is surrounded by those components. That's obviously not what I want. I want a new blank page when I type http://xxx/login. How to achieve this?
![image](https://user-images.githubusercontent.com/5236864/75032453-9d349600-54e3-11ea-9ec0-2bf20a1582bf.png)

**Comment by tomastrajan** [comment]
You would have to restructure whole application so that the is the `<router-outlet>` as the first component and everything is a route, then there will be some `main-layout` route which would have children which are all the current routes... Then you can have sibling routes like login without any layout...

Another way would be to have special service where some routes would set some special state... That state can be used in main layout to hide toolbar and footer..

This is out of scope for this project and will not be implemented in the starter.

Good luck with your project!
