### ISSUE TITLE
Is there a simple example that mimics communication between sibling components?

### ISSUE THREAD

**Issue by josoroma** [tomastrajan/angular-ngrx-material-starter#52]
Hi Hackers!

In order to make sense of the communication between components, I am looking for a simple example, one that mimics the old and problematic emit and broadcast communication but this time using ngrx. 

For example:

On click event `Component 1` sends an `ID Param` to the method of another component => `Component 2`, so `Component 2` re-loads a listing table based on the ID Param previously sent by `Component 1`.

Thanks a bunch!

**Comment by tomastrajan** [comment]
Hi @josoroma !

this can be accomplished in multiple ways. This repository uses [ngrx](https://github.com/ngrx/platform) state management library which holds state in dedicated centralized store. 

All interested components are subscribed (listening) to state updates from the store. State is updated only in the single source of truth (the store) by emitting actions in the components and services.

So for your use case it would go as follows:
 1. click in `comp 1`  emits action to update `ID param` in the store
 2. action is handled by corresponding `reducer` to produce new state (eg filter table result based on ID)
 3. `comp 2` is subscribed to table data from store and gets the new table data because it was changed by previously emitted action

In case we want that  the ID change triggers reload of table data we can use ngrx effects who also listen to emitted actions and trigger side effects.

Cheers!

**Comment by Fiontan** [comment]
NGRX Store uses Observables and so when a Component A subscribes to a slice of the Store e.g. Todos, that Component B is also subscribed to, then when Component C dispatches an action to update the Store's list of Todos, then all Components mentioned above will get the latest Todos value.

**Comment by tomastrajan** [comment]
I guess this question was answered by the provided comments. In case you have some more questions please feel free to create new issue. Thank you for contribution!
