### ISSUE TITLE
Is there any reason why services are exported in CoreModule

### ISSUE THREAD

**Issue by chan-dev** [tomastrajan/angular-ngrx-material-starter#535]
Arent' services injected within angular's root injector unless they're lazy loaded?

Here's a snippet of it.
```
export {
  TitleService,
  selectAuth,
  authLogin,
  authLogout,
  routeAnimations,
  AppState,
  LocalStorageService,
  selectIsAuthenticated,
  ROUTE_ANIMATIONS_ELEMENTS,
  AnimationsService,
  AuthGuardService,
  selectRouterState,
  NotificationService,
  selectEffectiveTheme,
  selectSettingsLanguage,
  selectSettingsStickyHeader
};

```

**Comment by tomastrajan** [comment]
Hi @chan-dev !

The resason is to be able to import them centrally from core.module (similar to index.ts) instead of deep imports from core.

That way it is possible to describe "public" `CoreModule` API which is ment to be consumed...

Imports then look like `import { ROUTE_ANIMATIONS_ELEMENTS } from '../../../core/core.module';`

It owuld be possible to achieve the same using `index.ts` but that solution had some issue in the past with node / TS resolution of paths... 

So this has nothing with lazy loading as core services can be consumed anywhere as they are application wide singletons so in both eager and lazy part...

Hope this satisfies your question ;)

**Comment by chan-dev** [comment]
Oh I see, I didn't look at it that way. Is there still an issue with resolution paths that's why you stick with this approach instead of using index.ts?

**Comment by tomastrajan** [comment]
@chan-dev havent explored that in some time now so I do not have up to date info on it, now that I remember part of the problem were wrong auto imports in intellij IDEA but dont know the current situation...

Another aproach can be to have `tsconfig.json` path aliases, eg `@core` but there were some issues with that too so I settled for approach in this repo but might be interesting to revisit.

**Comment by chan-dev** [comment]
oh i see. Thanks for the response.
