### ISSUE TITLE
Theme scss file paths in styles.scss are missing parent folder

### ISSUE THREAD

**Issue by JanOschii** [tomastrajan/angular-ngrx-material-starter#91]
Hi Tomas,

take a look on the import statements for your themes in `styles.scss`.
They are missing the parent folder "themes". 
It should look like this:

```
@import 'themes/default-theme.scss';
@import 'themes/light-theme.scss';
@import 'themes/black-theme.scss';
@import 'themes/nature-theme.scss';
```
Although it worked before, my IDE **PhpStorm** stopped complaining about these lines after the change.

Jan

PS: Nice project.

**Comment by tomastrajan** [comment]
Hey Jan!

Happy to hear that you like the project! The deal with the `themes` folder is that it is defined in `angular-cli.json` file in `stylesPreprocessorOptions` and `includePaths`. 

To make it work in WebStorm set `themes` folder as resource root.

ps: I use Intellij IDEA so had to deal with it too 😉

**Comment by JanOschii** [comment]
Hey Tomas,

i see. But its still defined in `.angular-cli.json` 
```
      "stylePreprocessorOptions": {
        "includePaths": ["./", "./themes"]
      },
```
Maybe it works with WebStorm but fails with PhpStorm. 
Do you see any problem, if I keep the import statements with the subfolder?

Jan

**Comment by tomastrajan** [comment]
Hey @JanOschii !

I gave it a bit more thought and realized you're right. Original solution is not obvious (more like magic) plus it doesn't work in some IDEs by default.

So I removed `"./themes" from `includePaths` and used full theme imports in `styles.scss` instead.

As for `"./"`, the story is bit more complicated because it is used for imports of `styles-variables.scss` which is used by many components and the relative imports would get pretty messy very fast (eg: `../../../../styles-variables.scss`) so I would still be in favour of using include paths for that even though IDE would complain without setting it up properly...

Anyway thank you for your contribution.

Cheers!
